services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: Post@20261406
      POSTGRES_DB: postboxdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Post@20261406"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  postgres_data:
  sqlserver_data: